---
docker_images:
  - name: blackbox-exporter
    file: blackbox-exporter.tar
  - name: node-exporter
    file: node-exporter.tar
  - name: custom-fluentd
    file: custom-fluentd.tar
docker_hosts:
  - node04
  - node08
  - node09
  - node10
docker_scripts:
  - script: run-node-exporter.sh
    condition: "inventory_hostname != 'gitlab-cicd'"
  - script: run-node-exporter-gitlab-cicd.sh
    condition: "inventory_hostname == 'gitlab-cicd'"
  - script: run-blackbox-exporter.sh
    condition: "true"
...
